name: 'manymac'
description: 'Build distributable macOS python wheels'
inputs:
  name:
    description: "The artifact name for in-action storage"
    required: true
runs:
  using: "composite"
  steps:
  - name: Install rename from brew
    run: brew install rename
    shell: bash

  - name: Update python tools
    run: python -m pip install --upgrade pip setuptools wheel delocate
    shell: bash

  - uses: actions/checkout@v2

  - name: Build and fix the wheel
    shell: bash
    run: |
      python -m pip wheel --no-deps . -w wheelhouse
      delocate-wheel -w dist -v wheelhouse/*.whl
      rename -e 's/10_15/10_13' dist/*.whl

  - uses: actions/upload-artifact@v2
    with:
      name: ${{ inputs.name }}
      path: dist/*.whl
